set nocompatible
filetype off
syntax enable

filetype plugin indent on

set tabstop=2
set nu
set shiftwidth=2
set expandtab

set splitbelow
set splitright

" Need this to get backspace working on Mac
set backspace=eol,indent,start
