DOTFILES=$HOME/dotfiles
source $DOTFILES/lib/shell/zsh.sh

for UTIL in $(ls $DOTFILES/util/*.sh); do
  source $UTIL
done

source $DOTFILES/lib/editor.sh
source $DOTFILES/lib/lang/go.sh
source $DOTFILES/lib/lang/ruby.sh