name: xmobar-igm
version: 0.1.0
synopsis: xmobar setting
dependencies:
  - X11
  - base
  - xmonad
  - xmonad-contrib
  - xmobar
executables:
  xmobar:
    main: xmobar.hs
    ghc-options:
      - -Wall
      - -fwarn-tabs
      - -threaded
      - -O2
      - -with-rtsopts=-N4
