resolver: lts-17.5
packages:
  - .

extra-deps:
  - xmobar-0.37
  - netlink-1.1.1.0

flags:
  xmobar:
    all_extensions: true

nix:
  enable: true
  packages:
    - x11
    - xorg.libXrandr
    - xlibs.libXScrnSaver
    - pkg-config
    - alsaLib
    - xorg.libXpm
