{
  pkgs,
  lib,
  config,
  ...
}:

let
  # Film-emulation styles for darktable (t3mujinpack, MIT licensed): 53
  # self-contained .dtstyle presets emulating Portra, Velvia, Kodachrome,
  # Ilford B&W, etc. Pinned and fetched declaratively. darktable does NOT
  # auto-load styles from disk, so these are staged under
  # ~/.config/darktable/styles-packs/ for a one-time import (see below).
  darktableStyles = pkgs.runCommand "t3mujinpack-darktable-styles" { } ''
    mkdir -p $out
    cp ${
      pkgs.fetchFromGitHub {
        owner = "t3mujinpack";
        repo = "t3mujinpack";
        rev = "0b421f3e25209ed78253d1724a29cc6255c5e7fe";
        hash = "sha256-2e0gxQD4fhfw5b7lzyoOo5T4GJotGD7S7o4vudVtLC8=";
      }
    }/*.dtstyle $out/
  '';
in
{
  config = lib.mkIf pkgs.stdenv.isDarwin {
    home.packages =
      with pkgs;
      [
        reattach-to-user-namespace
        pinentry_mac
        gnupg
        kbfs

        # Used for Thorium/Animecards
        ffmpeg

        pm2

        # file associations
        duti

        # Immich client + an archive wrapper that moves a folder into the
        # home Immich server and deletes the local copies once the server
        # confirms ingest. First-time auth on each machine:
        #
        #   immich login-key https://immich.yourhost.com/api <API_KEY>
        #
        # Get the API key from Immich's web UI: Account Settings → API Keys.
        immich-cli
        (writeShellApplication {
          name = "immich-archive";
          runtimeInputs = [
            immich-cli
            findutils
          ];
          text = ''
            if [ $# -eq 0 ]; then
              echo "usage: immich-archive <directory> [more dirs...]" >&2
              exit 64
            fi
            for dir in "$@"; do
              if [ ! -d "$dir" ]; then
                echo "not a directory: $dir" >&2
                exit 66
              fi
              # --delete removes each file only after the server confirms a
              # successful upload. Immich dedupes by hash, so re-runs are
              # idempotent.
              immich upload --recursive --delete -- "$dir"
              # CLI leaves empty dirs behind; prune them (but keep the
              # root arg so the user can see the archive completed).
              find "$dir" -mindepth 1 -type d -empty -delete
            done
          '';
        })
      ]
      ++ (lib.optionals pkgs.stdenv.hostPlatform.isAarch64 [
        keybase
      ]);

    xdg.enable = true;

    # asimeow: exclude dev build artifacts from Time Machine backups.
    # Installed + scheduled via nix-darwin homebrew (see nix/darwin/modules/time-machine.nix).
    igm.asimeow.enable = true;

    home.file.".gnupg/gpg-agent.conf" = {
      text = "pinentry-program ${pkgs.pinentry_mac}/${pkgs.pinentry_mac.passthru.binaryPath}";
    };

    # macOS file associations via duti
    home.file.".duti.conf".text = ''
      # Zed — source code and config files
      dev.zed.Zed .ts all
      dev.zed.Zed .tsx all
      dev.zed.Zed .js all
      dev.zed.Zed .jsx all
      dev.zed.Zed .json all
      dev.zed.Zed .nix all
      dev.zed.Zed .rs all
      dev.zed.Zed .toml all
      dev.zed.Zed .yaml all
      dev.zed.Zed .yml all
      dev.zed.Zed .md all
      dev.zed.Zed .py all
      dev.zed.Zed .go all
      dev.zed.Zed .css all
      # editor role (not "all") so Zed doesn't claim the HTML viewer role,
      # which macOS treats as the default browser and re-prompts about on every switch
      dev.zed.Zed .html editor
      dev.zed.Zed .sh all
      dev.zed.Zed .zsh all
      dev.zed.Zed .svelte all
      dev.zed.Zed public.source-code all
      dev.zed.Zed public.plain-text all
    '';

    home.activation.setFileAssociations = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      echo "Setting file associations with duti..."
      ${pkgs.duti}/bin/duti ~/.duti.conf
    '';

    # darktable film-emulation styles, staged read-only from the pinned pack.
    # One-time import per machine: darktable → Lighttable → "styles" panel →
    # import → select all .dtstyle files in
    # ~/.config/darktable/styles-packs/t3mujinpack/. They then live in
    # darktable's data.db; re-running igm-switch will not re-prompt or clobber.
    home.file.".config/darktable/styles-packs/t3mujinpack" = {
      source = darktableStyles;
      recursive = true;
    };

    # Symlink to the yabairc generated by nix-darwin's services.yabai
    home.activation.linkYabairc = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      yabairc=$(${pkgs.gnugrep}/bin/grep -oP '/nix/store/[^ ]*yabairc' ~/Library/LaunchAgents/org.nixos.yabai.plist || true)
      if [ -n "$yabairc" ]; then
        ln -sf "$yabairc" ~/.yabairc
      fi
    '';

    programs.firefox = {
      enable = true;
      package = null; # installed via nix-casks
      policies = {
        ExtensionSettings = {
          "uBlock0@raymondhill.net" = {
            install_url = "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi";
            installation_mode = "force_installed";
          };
        };
      };
    };

    programs.brave = {
      enable = true;
      package = null; # installed via nix-darwin systemPackages
      extensions = [
        { id = "nngceckbapebfimnlniiiahkandclblb"; } # Bitwarden
        { id = "fcoeoabgfenejglbffodgkkbkcdhcgfn"; } # Claude
      ];
    };

    programs.ghostty = {
      enable = true;
      package = null; # installed via nix-darwin as ghostty-bin
      settings = {
        macos-titlebar-style = "native";
        window-padding-balance = true;
        resize-overlay = "never";
        # Wrap `ssh` so xterm-ghostty terminfo is auto-installed on the remote
        # (cached per-host) and TERM is set sanely. ssh-env sets TERM=xterm-256color
        # on the wire as a safe fallback; ssh-terminfo upgrades back to xterm-ghostty
        # once it has installed the terminfo entry on the remote, then remembers.
        shell-integration-features = "ssh-env,ssh-terminfo";
        # Quit the app when the last window closes (matches iTerm2 / Terminal.app).
        quit-after-last-window-closed = true;
        # Allow OSC 52 read/write so yank in remote vim/nvim/tmux copies to the
        # local macOS clipboard over ssh.
        clipboard-read = "allow";
        clipboard-write = "allow";
      };
    };

    programs.ssh.matchBlocks."*".extraOptions = {
      IgnoreUnknown = "UseKeychain";
      UseKeychain = "yes";
    };

    programs.zsh.sessionVariables.ANDROID_HOME = "${config.home.homeDirectory}/Library/Android/sdk";
  };
}
