DOTFILES=$HOME/dotfiles
source $DOTFILES/lib/shell/zsh.sh

source $DOTFILES/lib/transfer.sh
source $DOTFILES/lib/util.sh
source $DOTFILES/lib/z.sh

export PATH=$HOME/.local/bin:$PATH

export AWS_PROFILE=asuna

# Editor stuff
export EDITOR=emacsclient
alias vi=vim
alias e="emacsclient -n"

# Python
export WORKON_HOME=$HOME/.virtualenvs
export VIRTUALENVWRAPPER_SCRIPT="$(which virtualenvwrapper.sh)"
source "$(which virtualenvwrapper_lazy.sh)"

# Go
export GO15VENDOREXPERIMENT=1
export GOPATH=$HOME/gocode
export PATH=$GOPATH/bin:$PATH

# Ruby
if [ -d "$HOME/.rvm/bin" ]; then
    PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
fi

# Scala
alias sbto='sbt "set offline := true"'
alias sbten='sbt "set scalaVersion := \"2.11.8\"" ensimeConfig'
alias sbtcd="sbt clean dockerBuildAndPush"
alias sbtcp="sbt clean publish"
export SBT_OPTS="-Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=2G -Xss2M"
