DOTFILES=$HOME/dotfiles
source $DOTFILES/lib/shell/zsh.sh

source $DOTFILES/lib/transfer.sh
source $DOTFILES/lib/util.sh
source $DOTFILES/lib/z.sh

export PATH=$HOME/.local/bin:$HOME/anaconda3/bin:$PATH

export AWS_PROFILE=abacus

# Editor stuff
export EDITOR=emacsclient
alias vi=vim
alias e="emacsclient -n"

# Python
# export WORKON_HOME=$HOME/.virtualenvs
# export VIRTUALENVWRAPPER_SCRIPT="$(which virtualenvwrapper.sh)"
# source "$(which virtualenvwrapper_lazy.sh)"

# Go
export GOPATH=$HOME/gocode
export PATH=$GOPATH/bin:$PATH

# Ruby
if [ -d "$HOME/.rvm/bin" ]; then
    PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
fi

# Scala
alias sbto='sbt "set offline := true"'
alias sbten='sbt "set scalaVersion := \"2.11.8\"" ensimeConfig'
alias sbtca="sbt clean assembly"
alias sbtcd="sbt clean dockerBuildAndPush"
alias sbtcp="sbt clean publish"
export SBT_OPTS="-Xmx8G -XX:+CMSClassUnloadingEnabled -Xss2M"

sfxl() {
  play -v 10.0 $DOTFILES/sfx/$1.ogg
}
alias funky="sfxl fortnite"

kubetokeninternal() {
  kubectl -n kube-system get secret $(kubectl -n kube-system get secret | grep eks-admin | awk '{print $1}') -o=json | jq .data.token -r | base64 --decode
}

kubetoken() {
  kubetokeninternal | xclip -sel c
}

kubetokenm() {
  kubetokeninternal | pbcopy
}

alias sfmt="scalafmt -c .scalafmt --exclude .ensime_cache"
alias kubeupdate=/home/ian/proj/abacusprotocol/infrastructure/kubernetes/scripts/update.sh

alias prad="keybase chat send asuna"
alias dylan="keybase chat send dylanmacalinao"

source $HOME/private_secrets/lib/helpers.sh

export GPG_TTY=$(tty)
export SHELL=$(which zsh)
