DOTFILES=$HOME/dotfiles
source $DOTFILES/lib/shell/zsh.sh

source $DOTFILES/lib/transfer.sh
source $DOTFILES/lib/util.sh
source $DOTFILES/lib/z.sh

export AWS_PROFILE=abacus

# Editor stuff
export EDITOR=emacsclient
alias vi=vim
alias e="emacsclient -n"

# Python
# export WORKON_HOME=$HOME/.virtualenvs
# export VIRTUALENVWRAPPER_SCRIPT="$(which virtualenvwrapper.sh)"
# source "$(which virtualenvwrapper_lazy.sh)"

# Go
export GOPATH=$HOME/gocode
export PATH=$GOPATH/bin:$PATH

# Scala
alias sbto='sbt "set offline := true"'
export SBT_OPTS="-Xmx8G -XX:+CMSClassUnloadingEnabled -Xss2M"

sfxl() {
  play -v 10.0 $DOTFILES/sfx/$1.ogg
}
alias funky="sfxl fortnite"

kubetokeninternal() {
  kubectl -n kube-system get secret $(kubectl -n kube-system get secret | grep eks-admin | awk '{print $1}') -o=json | jq .data.token -r | base64 --decode
}

kubetoken() {
  kubetokeninternal | xclip -sel c
}

kubetokenm() {
  kubetokeninternal | pbcopy
}

alias sfmt="scalafmt -c .scalafmt --exclude .ensime_cache"

alias prad="keybase chat send asuna"
alias dylan="keybase chat send dylanmacalinao"
alias abachat="keybase chat send abacusprotocol"

alias unescape="jq -r ."

source $HOME/private_secrets/lib/helpers.sh

export GPG_TTY=$(tty)
export SHELL=$(which zsh)

export JAVA_HOME=$(readlink -e $(type -p javac) | sed  -e 's/\/bin\/javac//g')

export GEM_HOME=$HOME/gems
export PATH=$HOME/gems/bin:$PATH
