# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules =
    [ "ata_piix" "ohci_pci" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5d6e5099-0b78-47f6-9f1d-5864e57447ae";
    fsType = "ext4";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/116b36ed-7321-4726-83dd-97c4980a433c"; }];

  nix.settings.max-jobs = lib.mkDefault 4;

  boot.loader.grub.enable = true;

  boot.loader.grub.device = "/dev/sda";
  boot.initrd.checkJournalingFS = false;
}
