#!/usr/bin/env -S bash -xe

CACHIX_CACHE="${2:-igm}"
echo "Building $1 and pushing to $CACHIX_CACHE"

nix -Lv build $1 --json |
    jq -r '.[].outputs | to_entries[].value' |
    cachix push $CACHIX_CACHE
