#!/usr/bin/env bash -xe

DOTFILES=$HOME/dotfiles
cd $DOTFILES

FLAKE_PATH=''
if $(uname -a | grep -q "Darwin"); then
    FLAKE_PATH="./private/flakes/darwin"
elif $(uname -a | grep -q "NixOS"); then
    FLAKE_PATH="./private/flakes/nixos"
else
    echo "No system flake found for this platform."
    exit 1
fi

echo "Updating private dotfiles."
cd $HOME/dotfiles-private && git add -A . && git commit -m "Updates" && git frp

cd $DOTFILES

echo "Updating igm and dotfiles-private-raw flakes."
nix flake lock --update-input igm --update-input dotfiles-private-raw $FLAKE_PATH

if $(uname -a | grep -q "NixOS"); then
    sudo nixos-rebuild switch --impure --flake "$FLAKE_PATH#primary"
fi

if $(uname -a | grep -q "Darwin"); then
    nix build "$FLAKE_PATH#darwinConfigurations.ian-mbp-m1.system" --show-trace || exit 1
    ./result/sw/bin/darwin-rebuild switch --flake "$FLAKE_PATH#ian-mbp-m1"
    rm -r result
fi
