#!/usr/bin/env -S bash -xe

echo "Building the latest system configuration..."

DOTFILES=$HOME/dotfiles
cd $DOTFILES

SHOW_TRACE=''
if [ $1 = '--debug' ]; then
    SHOW_TRACE='--show-trace'
fi

source $DOTFILES/scripts/igm-helpers.sh
FLAKE_PATH=$(flake_path)
SYSTEM_CONFIG_ATTRIBUTE=$(system_config_attribute)
echo "Using flake at path $FLAKE_PATH."

echo "Updating private dotfiles."
cd $HOME/dotfiles-private && git add -A . && git commit -m "Updates" && git frp

cd $DOTFILES

echo "Updating igm and dotfiles-private-raw flakes."
nix flake lock --update-input igm --update-input dotfiles-private-raw $FLAKE_PATH

if $(uname -a | grep -q "NixOS"); then
    nix build "$FLAKE_PATH#nixosConfigurations.$SYSTEM_CONFIG_ATTRIBUTE.system" $SHOW_TRACE || exit 1
elif $(uname -a | grep -q "Darwin"); then
    nix build "$FLAKE_PATH#$SYSTEM_CONFIG_ATTRIBUTE" $SHOW_TRACE || exit 1
fi

echo "Success! Now run 'igm-switch'."
