#!/usr/bin/env -S bash -xe

DOTFILES=$HOME/dotfiles
cd $DOTFILES

source $DOTFILES/scripts/igm-helpers.sh
FLAKE_PATH=$(flake_path)
SYSTEM_CONFIG_ATTRIBUTE=$(system_config_attribute)
echo "Using flake at path $FLAKE_PATH."

SHOW_TRACE=''
if [ $1 = '--debug' ]; then
    SHOW_TRACE='--show-trace'
fi

echo "Updating private dotfiles."
cd $HOME/dotfiles-private && git add -A . && git commit -m "Updates" && git frp

cd $DOTFILES

echo "Updating igm and dotfiles-private-raw flakes."
nix flake lock --update-input igm --update-input dotfiles-private-raw $FLAKE_PATH

if $(uname -a | grep -q "NixOS"); then
    sudo nixos-rebuild switch --impure --flake "$FLAKE_PATH#$SYSTEM_CONFIG_ATTRIBUTE" $SHOW_TRACE
fi

if $(uname -a | grep -q "Darwin"); then
    nix build "$FLAKE_PATH#$SYSTEM_CONFIG_ATTRIBUTE" $SHOW_TRACE || exit 1
    ./result/sw/bin/darwin-rebuild switch --flake "$FLAKE_PATH#$(hostname)"
    rm -r result
fi
