#!/usr/bin/env bash

DOTFILES=$HOME/dotfiles
source $DOTFILES/scripts/igm-helpers.sh

cd $DOTFILES/nix
nix_cmd flake update

cd $HOME/dotfiles-darwin
nix flake update

cd $DOTFILES
git add .

git commit -am "Run nix flake update via igm-update"
