#!/usr/bin/env -S bash -xe

DOTFILES=$HOME/dotfiles
source $DOTFILES/scripts/igm-helpers.sh

cd $DOTFILES

nix_cmd flake update $DOTFILES/nix
nix_cmd flake update

nix_cmd fmt $DOTFILES/nix
nix_cmd fmt
git add .

FLAKE_PATH=$(flake_path)
echo "Using flake at path $FLAKE_PATH."
cd $FLAKE_PATH
nix_cmd flake update
