#!/usr/bin/env -S bash -xe

if [ -e $DOTFILES/nix/shells/$1/default.nix ]; then
    SHELL_PATH=$DOTFILES/nix/shells/$1/default.nix
else
    SHELL_PATH=$DOTFILES/nix/shells/$1.nix
fi
if [ ! -e $SHELL_PATH ]; then
    echo "Shell does not exist."
    exit 1
fi
nix develop $DOTFILES/nix#$1 --command $SHELL
