# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  hardware.enableRedistributableFirmware = lib.mkDefault true;

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernelParams = [ "radeon.si_support=0" "amdgpu.si_support=1" ];
  boot.extraModulePackages = [ ];

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/d83d6906-f53f-417b-a080-e2b05f5990b8";
      fsType = "btrfs";
      options = [ "subvol=nixos" ];
    };
    "/mnt/nas" = {
      device = "/dev/disk/by-uuid/af694995-6ef0-4649-9f97-ce0df0525ff5";
      fsType = "ext4";
      options = [ "nodev" "nosuid" "noatime" ];
    };
  };

  boot.initrd.luks.devices = {
    "cryptroot".device =
      "/dev/disk/by-uuid/ea26aee0-c2c4-4211-8bec-9551913c0a56";
    "nas".device = "/dev/disk/by-uuid/06e340d6-f60f-4b32-b8c9-31b4022f57b2";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/ADA4-EB17";
    fsType = "vfat";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/04701011-2d17-4b5e-b29f-ed7d52f10a81"; }];

  nix.settings.max-jobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = "performance";

  services.xserver.videoDrivers = [ "nvidia" ];

  hardware.opengl.driSupport = true;
  hardware.opengl.driSupport32Bit = true;
  hardware.nvidia.prime = {
    sync.enable = true;
    # Bus ID of the NVIDIA GPU. You can find it using lspci
    nvidiaBusId = "PCI:1:0:0";
    # Bus ID of the Intel GPU. You can find it using lspci
    intelBusId = "PCI:0:2:0";
  };

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
}

